### ISSUE TITLE
Unsafe 3DES Cipher Suite im FHIR Proxy

### ISSUE THREAD

**Issue by UKFr-DIZ** [datasharingframework/dsf#117]
Hi,

I've been informed by our security team that we are still supporting an insecure cipher suite. They directed me to the standards at https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices.

After reviewing, I noticed that a 3DES cipher suite is still being supported, which should be removed according to the best practice recommendations.

As a result, I suggest removing this cipher suite from the ssl.conf. Please refer to the `SSLCipherSuite` and `SSLProxyCipherSuite` directives.

Source:
https://github.com/datasharingframework/dsf/blob/74eb4d7af27fe8638985165b862025c908d1d058/dsf-docker/fhir_proxy/conf/extra/httpd-ssl.conf#L68

Best regards,
Nam

**Comment by schwzr** [comment]
Suggestion of which cipher suites to support:

https://ssl-config.mozilla.org/#server=apache&version=2.4.41&config=intermediate&openssl=1.1.1k&guideline=5.7
