### ISSUE TITLE
Treat RC releases similar to SNAPSHOT releases

### ISSUE THREAD

**Issue by wetret** [datasharingframework/dsf#131]
Release Candidates are currently deployed like normal releases. Therefore, changes in FHIR resources between two RC releases with the same BPE release number are not deployed. I would suggest to treat RC releases like SNAPSHOT releases, changing:
https://github.com/datasharingframework/dsf/blob/6a7d4c5e383cfc406df2d1bb43f8204fc95278bd/dsf-bpe/dsf-bpe-server/src/main/java/dev/dsf/bpe/plugin/ProcessPluginLoaderImpl.java#L121

**Comment by hhund** [comment]
We should also switch to the `SNAPSHOT` behavior for milestone (`M[0-9]+`) releases.
