### ISSUE TITLE
Use UUID generator instead of database id generator

### ISSUE THREAD

**Issue by EmteZogaf** [datasharingframework/dsf#139]
As suggested in [this Camunda document](https://docs.camunda.org/manual/latest/user-guide/process-engine/id-generator/) the BPE should be configured to use the `StrongUuidGenerator` instead of the default `DbIdGenerator` to allow better performance when executing concurrent processes.

**Comment by hhund** [comment]
Fixed as part of the [v1.3.2](https://github.com/datasharingframework/dsf/releases/tag/v1.3.2) release. Merge into `develop` via #141 for the 1.4.0 release tbd.

**Comment by hhund** [comment]
Merged into `develop` via 586a84a
