### ISSUE TITLE
OrganizationProvider Never Finds Organization by Identifier

### ISSUE THREAD

**Issue by hhund** [datasharingframework/dsf#61]
The `getOrganization(Identifier organizationIdentifier)` method searches for `Endpoint` resources and thus can't find `Organization` resources by identifier.

https://github.com/datasharingframework/dsf/blob/6f03aa9d3c2cf244b0828c9ce9ea1c0070763958/dsf-bpe/dsf-bpe-server/src/main/java/dev/dsf/bpe/v1/service/OrganizationProviderImpl.java#L75-L77

**Comment by wetret** [comment]
There is another error in line 76: the parameter should be named `active` and not `status` and the value should be `true` and not `active`.

https://github.com/datasharingframework/dsf/blob/6f03aa9d3c2cf244b0828c9ce9ea1c0070763958/dsf-bpe/dsf-bpe-server/src/main/java/dev/dsf/bpe/v1/service/OrganizationProviderImpl.java#L75-L77
